# Numpy:

*`Numpy`* is a powerful library in Python that is used for numerical computing. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.


In [3]:
# import the numpy library
import numpy as np


In [7]:
arr = np.array([1,2,3,4,5])
print("Array: ", arr)

print(type(arr))

Array:  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
# Use a tuple to create a NumPy array:

arr = np.array((1, 2, 3, 4, 5))
print(arr.ndim)

print("-------")
# 1D array 
arr = np.array([1,2,3,4,5])
print("1D array: ", arr.ndim)

print("-------")
# 2D array
arr2 = np.array([[1,2,3,4,5]])
print("2D array : ", arr2.ndim)

print("-------")
arr2 = np.array([[1,2,3,4], [5,4,3,2], [1,3,7,9]])
print("2D array : ", arr2.ndim)

print("-------")
# 3D array
arr3 = np.array([[[1,2,3,4], [5,4,3,2], [1,3,7,9]]])
print("3D array : ", arr3.ndim)

print("-------")
arr3 = np.array([[[1,2,3,4,5]]])
print("3D array : ", arr3.ndim)

1
-------
1D array:  1
-------
2D array :  2
-------
2D array :  2
-------
3D array :  3
-------
3D array :  3


In [17]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
#  we can create the array with any number of dimensions by using the 'ndim' aargument.

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
# we can access an array element by referring to its index number

arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[3])

# take the 2nd and 3rd element from the array and add them
print(arr[1] + arr[3])


1
4
6


In [30]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print(arr[1, 4])
print(arr[0,3])
print(arr[1, 2])

print("-------")
# take the two element from the arr and add them

print(arr[0, 1] + arr[1, 4])

2nd element on 1st row:  2
10
4
8
-------
12


In [34]:
# Access the 3D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[1, 0, 0])
# add the 3 element from the arr and add them
print(arr[0,1,2]+arr[1,0,0]+arr[1,1,2])

6
7
25


In [41]:
# Negative indeing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,-5])
print(arr[1,-1])

1
10


In [42]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])

7


# NumPy Array Slicing

Slicing in python means taking elements from one given index to another given index.

* We pass slice instead of index like this: `[start:end]`.

* We can also define the step, like this: `[start:end:step]`.

* If we don't pass start its considered 0

* If we don't pass end its considered length of array in that dimension

* If we don't pass step its considered 1

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[:4:2])
print(arr[2:])

# Negative slicing

# reverse the array
print(arr[::-1])
# reverse the array from index 5 to 1
print(arr[5:1:-1])

[2 3 4 5]
[1 3]
[3 4 5 6 7]
[7 6 5 4 3 2 1]
[6 5 4 3]


In [ ]:
#  Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print("-------")

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
-------
-------
[3 8]
[[2 3 4]
 [7 8 9]]


In [56]:
# create the array from the existing data

a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [60]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
# we stack the array vertically
np.vstack((a1, a2))


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [61]:
# if we stack the array horizontally then we use the hstack() function.
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])